# Generated by Django 2.2 on 2020-03-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200323_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_teacher',
        ),
    ]
