# Generated by Django 2.2 on 2020-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('courses', '0005_auto_20200323_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='user_name',
            field=models.ManyToManyField(blank=True, null=True, to='organizations.Teacher', verbose_name='讲师'),
        ),
    ]
