# Generated by Django 2.2 on 2020-03-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('courses', '0006_auto_20200323_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user_name',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='讲师'),
        ),
    ]
