# Generated by Django 2.2 on 2020-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='is_teacher',
            field=models.ManyToManyField(to='organizations.Teacher', verbose_name='讲师'),
        ),
    ]
