# Generated by Django 2.2 on 2020-03-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_coursecomments_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='is_teacher',
        ),
    ]
