# Generated by Django 2.2 on 2020-03-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_coursecomments_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='teacher',
        ),
    ]
